#---- Dirs ----
reference_dir: "reference"
samples_dir: "samples"
samples_splitted_dir: "results/splitted"

out_trf_dir: "results/trf"
out_wm_dir: "results/windowmasker"
out_rm_dir: "results/repeatmasker"

out_gff_trf_dir: "results/gff/trf"
out_gff_wm_dir: "results/gff/windowmasker"
out_gff_rm_dir: "results/gff/repeatmasker"
out_gff_merged_dir: "results/gff/merged"
out_bedtools_dir: "results/bedtools"
out_lastdbal_dir: "results/lastdbal"

scripts_dir: "workflow/scripts"

log_dir: "logs"
cluster_log_dir: "cluster_logs"

conda_config: "workflow/envs/conda.yaml"

samples:
    japonicus: samples/japonicus.fasta
    octosporus: samples/octosporus.fasta

reference: reference/cerevisiae.fasta

#---- Threads ----
trf_threads: 16
trf_gff_threads: 1
merge_gff_threads: 1
repeatmasker_threads: 16
split_fasta_threads: 1
wm_counts_threads: 16
wm_windowmasker_threads: 16
wm_gff_threads: 1
bedtools_sort_threads: 16
bedtools_threads: 16
lastdb_threads: 16
lastal_threads: 16
last_tar_threads: 1

#---- Time ----
trf_time: "00:30:00"
trf_gff_time: "00:10:00"
merge_gff_time: "00:05:00"
repeatmasker_time: "00:30:00"
split_fasta_time: "00:10:00"
wm_counts_time: "00:30:00"
wm_windowmasker_time: "00:30:00"
wm_gff_time: "00:10:00"
bedtools_sort_time: "00:10:00"
bedtools_time: "00:30:00"
lastdb_time: "00:30:00"
lastal_time: "00:30:00"
last_tar_time: "00:05:00"

#---- Memory ----
trf_mem_mb: 1000
trf_gff_mem_mb: 100
merge_gff_mem_mb: 100
repeatmasker_mem_mb: 1000
split_fasta_mem_mb: 100
wm_counts_mem_mb: 1000
wm_windowmasker_mem_mb: 1000
wm_gff_mem_mb: 100
bedtools_sort_mem_mb: 1000
bedtools_mem_mb: 1000
lastdb_mem_mb: 1000
lastal_mem_mb: 1000
last_tar_mem_mb: 1000